version: '3.8'

services:
  backend:
    image: test/project
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PROJECT_SERVICES_PORT}:${PROJECT_SERVICES_PORT}
    environment:
      PROJECT_SERVICES_PORT: ${PROJECT_SERVICES_PORT}
      NODE_ENV: production
      DB_WRITE_HOST: dbProject
      DB_READ_HOST: dbProjectRead
      DB_PORT: 5432
      DB_USER: user-project-admin
      DB_PASSWORD: password-project-admin
      DB_NAME: project
    env_file:
      - .env
    container_name: project
    depends_on:
      dbProject:
        condition: service_healthy
      dbProjectRead:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
    networks:
      - app-network

  dbProject:
    image: bitnami/postgresql:13
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=user-project-admin
      - POSTGRESQL_PASSWORD=password-project-admin
      - POSTGRESQL_DATABASE=project
    volumes:
      - postgres_master_data:/bitnami/postgresql
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user-project-admin']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  dbProjectRead:
    image: bitnami/postgresql:13
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=dbProject
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_USERNAME=user-project-admin
      - POSTGRESQL_PASSWORD=password-project-admin
      - POSTGRESQL_DATABASE=project
    volumes:
      - postgres_slave_data:/bitnami/postgresql
    ports:
      - '5433:5432'
    depends_on:
      - dbProject
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user-project-admin']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_master_data:
  postgres_slave_data:

networks:
  app-network:
    driver: bridge
