export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  BAD_REQUEST = 'BAD_REQUEST',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS',
  USER_NAME_EXISTS = 'USER_NAME_EXISTS',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  VEHICLE_OWNER_NOT_FOUND = 'VEHICLE_OWNER_NOT_FOUND',
  VEHICLE_NOT_FOUND = 'VEHICLE_NOT_FOUND'
}
